import Head from 'next/head';
// import DropDownMenu from '../components/utils/DropDownMenu/DropDownMenu';
// import Header from '../components/Header/Header';
import Button from '@mui/material/Button';
import styles from '../styles/Home.module.css';

import { styled } from '@mui/material/styles';
import { BootstrapDropDownMenu } from '../components/utils/DropDownMenu/DropDownMenu.styles';
// import DropDownMenu from '../components/utils/DropDownMenu/DropDownMenu';

const BootstrapButton = styled(Button)({
  boxShadow: 'none',
  textTransform: 'none',
  fontSize: 16,
  padding: '6px 12px',
  border: '1px solid',
  lineHeight: 1.5,
  backgroundColor: 'red',
  borderColor: '#0063cc',
  fontFamily: [
    '-apple-system',
    'BlinkMacSystemFont',
    '"Segoe UI"',
    'Roboto',
    '"Helvetica Neue"',
    'Arial',
    'sans-serif',
    '"Apple Color Emoji"',
    '"Segoe UI Emoji"',
    '"Segoe UI Symbol"',
  ].join(','),
  '&:hover': {
    backgroundColor: '#0069d9',
    borderColor: '#0062cc',
    boxShadow: 'none',
  },
  '&:active': {
    boxShadow: 'none',
    backgroundColor: '#0062cc',
    borderColor: '#005cbf',
  },
  '&:focus': {
    boxShadow: '0 0 0 0.2rem rgba(0,123,255,.5)',
  },
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BootstrapButton variant="contained" disableRipple>
        hello
      </BootstrapButton>
      {/* <DropDownMenu /> */}
      {/* <Header /> */}
      {/* <DropDownMenu /> */}
      <BootstrapDropDownMenu />
    </div>
  );
}
