import Head from 'next/head';
import CardComponentWithBackgroundImage from '../components/Common/Card/Card';
import data from '../public/data.json';
import { Box, Grid, Typography } from '@mui/material';
import HomeDetails from '../components/Common/HomeDetails/HomeDetails';
import styles from '../styles/Home.module.css';
import ParallaxSection from '../components/Common/ParallaxSection/ParallaxSection';
import Testimonial from '../components/Testimonial/Testimonial';
import Slider from 'react-slick';
// import '~slick-carousel/slick/slick-theme.css';

export default function Home() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Big Gates Properties</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Box position={'relative'}>
        <Grid container columnSpacing={5} justifyContent="center">
          {data.services.map(({ title, description, route }, index) => (
            <Grid item key={index}>
              <CardComponentWithBackgroundImage
                cardDescription={description}
                cardTitle={title}
              />
            </Grid>
          ))}
        </Grid>
      </Box>
      <HomeDetails />
      <ParallaxSection />
      <Testimonial />
      {/* <Slider {...settings}>
        <div>
          <h3>1</h3>
        </div>
        <div>
          <h3>2</h3>
        </div>
      </Slider> */}
    </>
  );
}
